### ISSUE TITLE
"security"

### ISSUE THREAD

**Issue by KelseyMcH** [KelseyMcH/2016_Spring_WellnessAutomation#1]
By adding something like /index to the end of the URL you can jump to different pages while not being signed in. So we not only need a check for this but we need a new page to tell the user they arent signed in. This doesnt sound like a big deal, but bookmarks would get messed up.

**Comment by williapa** [comment]
The only page this would be a "security issue" for is creating or editing activities. I'm pretty sure it's fixed by putting back in the before_filter in the controller
